mysql_host: 192.168.43.91
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34343365633135616636376532393761343731383435373738373662393262366334313530633163
          3535366239373738376639343166363463386365363965620a383539376163643361643733333937
          63303636633335363637636232346434316332363364663338363638663864623836306161363936
          3735306136366363640a323664346334323962383135373764633061613937313538376330393937
          3035
