
# MySQL
mysql_host: "{{ git_user }}-2" 
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31663636633139356436313032666363623437623466306465656337646135653863666563613566
          3438303336306438376332623263366333333265633836390a653333333865323832663134376165
          39393266633739386263333537616534356561376166613234306139656333396632333138343864
          6562333466353332620a323162343161366132326464633031336666653736363238643365373263
          6131

mysql_exporter_user: exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35336233306539396239303132393761363138323139613439373333303165386635363635323362
          3364663435643937303162376364376633353564383864620a336261623164636634343331643537
          35313432346139636262613533626132643033386261626539396139666164336464636438343534
          3634346432353363650a343439316631396530393961353362616362643264396363323661633961
          6537

# Grafana          
grafana_user: grafanaadmin
grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31326632663931323330633964343066386337393438313734396563363633643130636638356235
          3465313361636563653532656430323462613738353935640a373533616538326666366166663035
          36346636386534303163653864343534396261616538343362353964373466333135393761386266
          3937633464613865390a386437346165663538666364363235316437366461616638386435353039
          6431

# DNS          
dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9

dns_allowed_networks:
  - 192.168.42.0/23
  - 127.0.0.0/8

startup_name: acme.ttu


# Prometheus  
prometheus_exporters:
  mysql:
    port: 9104
  bind:
    port: 9119
  nginx:
   port: 9113

# InfluxDB
influxdb_agama_database:    agama_client_db
influxdb_telegraf_database: telegraf
influxdb_http_port:         8086

# Backup  
backup_user: backup
backup_host: backup
backup_host_ip: 192.168.42.132
backup_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61613138636366663539356166623439623932313465323732653237343936316139313237363838
          6661326464356532303262336134626665343864623563620a323133383938363563393665656534
          32656638623562623962333533393232336666363034646635303331626264366633383732376238
          3535353438383837330a626162393931653033346538353432376537633437653764623464356132
          31323735386230646665656530386230323763306631366263373232663136626132
backup_pub_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEu6pFFWyuRrl4WGFPQGElYN9txwTGm2wSntcpVAaN90
git_user: orinocoz

mysql_backup_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633138353834303961656363343463373136386236373331333262366565643036646330623735
          6461623933376632623464633535353939316366306335300a383536393035306236363737313431
          65393030396637306137666235316537633866306263636562353965646636343233633839313132
          3732653362373261660a346330386133353461323831376661613865343866393563643861333962
          3164
mysql_backup_host: "{{ groups['db_servers'] | reject('eq', mysql_host) | first | default(mysql_host) }}"

mysql_replication_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633138353834303961656363343463373136386236373331333262366565643036646330623735
          6461623933376632623464633535353939316366306335300a383536393035306236363737313431
          65393030396637306137666235316537633866306263636562353965646636343233633839313132
          3732653362373261660a346330386133353461323831376661613865343866393563643861333962
          3164
node_id: "{{ (hostvars[inventory_hostname].ansible_port / 100) | int }}"

grafana_port: 3001
agama_port: 8001
agama_port2: 8002
containers: 2

auth_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633138353834303961656363343463373136386236373331333262366565643036646330623735
          6461623933376632623464633535353939316366306335300a383536393035306236363737313431
          65393030396637306137666235316537633866306263636562353965646636343233633839313132
          3732653362373261660a346330386133353461323831376661613865343866393563643861333962
          3164

