mysql_host: orinocoz-2 
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31663636633139356436313032666363623437623466306465656337646135653863666563613566
          3438303336306438376332623263366333333265633836390a653333333865323832663134376165
          39393266633739386263333537616534356561376166613234306139656333396632333138343864
          6562333466353332620a323162343161366132326464633031336666653736363238643365373263
          6131
#mysql_backup_host: "{{ groups['db_servers'] | reject('eq', mysql_host) | first | default(mysql_host) }}"
dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9

dns_allowed_networks:
  - 192.168.42.0/23
  - 127.0.0.0/8

startup_name: acme.ttu
