startup_name: acme.ttu
dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
dns_allowed_networks:
  - 192.168.42.0/23
  - 127.0.0.0/8
  - 172.17.0.0/16

mysql_host: "{{ groups['db_servers'][0] }}"
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33626538363437373736626562616561613134616461393933666131393161633933303561346565
          6165363862643632613736353062313431383739323933610a386633343236303037626531326533
          65393162396235663634666632373464613934616565313535343838666163363938643436656565
          3136316134326330320a613033323030313038613039373738343530316366653435623933646364
          66656166646562623132353964393631363437353731316561663864373236646537

prometheus_exporters:
  mysql:
    port: 9104
  bind:
    port: 9119
  nginx:
    port: 9113
  backup:
    port: 9111
  haproxy:
    port: 9101
  keepalived:
    port: 9165

mysql_exporter_user:  exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31626634613734356563346163313936633630646137636434653736376565646634626261386163
          3432333763646632656236613461373835323563313265620a623433323332376636356537303538
          37306663333835353262653534326237633430656133373364636231343337343639333737656238
          6131333839326133640a343939393566656132653364306264643862343265653465623963333537
          32356561363435626236393039343031376534633065326332363839333033343230

grafana_user: orinocoz
grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65306336383838623539356437333435623563643633346339643134323639623238623738653661
          3234643066663465663064306435353338373931313264610a396134393831306132616137323931
          66383136623539646238646664663134383032373039373162383232333430656265343639326434
          3437613534656166630a326563363537633832373233323739356531643163346131363031663863
          30306262636666626236306661313734613765666336626638633238333565616464

backup_server_ip: 192.168.42.5
backup_server_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAtnpnME3TsMyvcJyiYawMBod33jkDcFG9Pb1rlxDiXX

backup_user: backup
backup_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38313765313665306535303061326334396232613330303831653536343534613666626431316362
          3039373963363264623639326561623165313837376463630a613366316230613266376138366530
          39306163616436633432613835366134336131656165383730363665346430623932383566616464
          3339646665633436310a333863623364333332323530376338633133373362643333613135633239
          37636365643462346132646438316361323730386339316564316234383062653766

mysql_backup_host: "{{ groups['db_servers'] | reject('eq', mysql_host) | first | default(mysql_host) }}"
github_user_backup: orinocoz
prometheus_server: "{{ groups['prometheus_servers'] | first }}"
loki_server: "{{ groups['loki_servers'] | first }}"

replica_user: replication
replica_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65323331346466323666303962643666303464393035333832303963373661376162313334373331
          3537333438346562326139363263373537363438363636380a653334616362623064393931633839
          35326136386230313535633538313036643566623265633763663539653735336630336234353966
          3233383464333261640a313530323832376533333635616334393832623131316332353735373631
          34646638303631326134636135393630313864336439363638306239643861373632

node_id: "{{ (ansible_port / 100) | int }}"

grafana_port: 3001
agama_port: 8001

agama_container_count: 2
keepalived_vrrp_id: 35
keepalived_auth_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65306266323631356238646263396266646462323231303334666239336236353364633162396161
          3732316261323961663837636338353336356337313937620a313766363539626433646139623963
          35653438656632326636383766383335356436363130396539353738323132303164626136643635
          6235636264333738390a326262356662646539373138373334633736343064376433663730346361
          3537

haproxy_frontend_port: 88
haproxy_stats_port: 9188
keepalived_exporter_version: "1.7.0"

dns_transfer_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31656534333362623366363661613865336562333239306661653134626332356661316530663233
          3862386464623162363334663661633365396232383464320a306230396238653266646466656461
          66396635626331636137653062653961643264363834373236393932333834333934613633656631
          6139636431663034640a633338613132303866643331356365363731306661353437663032613530
          31666537313062343261663865313239313963333334306162363862323339623162666161646462
          3534633965333564363530303631363234663735313233623961

dns_nsupdate_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37383565346137313134373165333361663464303733353663303566666435386366366431383866
          3264373538636638616462323837636433343565353932350a663866316238363266323636343835
          62666138386232653861386438323135373961613331623030386464633366343032656161616330
          3430323862303962350a633363623666343633366134356433646635656566643633633864613932
          66313837393339656166633462323932653134353861626436326136353235363562366362396138
          3533633338323133643238346134333233353062656365393762

