startup_name: acme.ttu
forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
allowed_networks:
  - 192.168.42.0/23
  - 127.0.0.0/8

mysql_host: orinocoz-2
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35353466333336663732356264646163633364343332633862343737663864653330383663336662
          6239366661323337636131366335626432333432346462390a653638393532326164386364326339
          62313434633639383930303161666132353439393632393561333764616235633761613461396166
          3366623030346237350a343933373735613364373837303064653738376130393662623763363636
          6330
