startup_name: acme.ttu
dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
dns_allowed_networks:
  - 192.168.42.0/23
  - 127.0.0.0/8

mysql_host: orinocoz-2
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35353466333336663732356264646163633364343332633862343737663864653330383663336662
          6239366661323337636131366335626432333432346462390a653638393532326164386364326339
          62313434633639383930303161666132353439393632393561333764616235633761613461396166
          3366623030346237350a343933373735613364373837303064653738376130393662623763363636
          6330

prometheus_exporters:
  mysql:
    port: 9104
  bind:
    port: 9119
  nginx:
   port: 9113

mysql_exporter_user:  exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35636263353862373562653165363564386139373263336133653066636465633431653235643266
          3962343031663038303365323138663639613631333862610a303935613332346433306464613531
          32363632353633323833623633663630656434386462386661633030373835363764396535626666
          3461613166663934650a343337666361373465373132363330626464353838326464383830353965
          3834


