startup_name: acme.ttu
dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
dns_allowed_networks:
  - 192.168.42.0/23
  - 127.0.0.0/8
  - 172.17.0.0/16

mysql_host: orinocoz-2
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35353466333336663732356264646163633364343332633862343737663864653330383663336662
          6239366661323337636131366335626432333432346462390a653638393532326164386364326339
          62313434633639383930303161666132353439393632393561333764616235633761613461396166
          3366623030346237350a343933373735613364373837303064653738376130393662623763363636
          6330

prometheus_exporters:
  mysql:
    port: 9104
  bind:
    port: 9119
  nginx:
    port: 9113
  backup:
    port: 9111
  haproxy:
    port: 9101
  keepalived:
    port: 9165

mysql_exporter_user:  exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35636263353862373562653165363564386139373263336133653066636465633431653235643266
          3962343031663038303365323138663639613631333862610a303935613332346433306464613531
          32363632353633323833623633663630656434386462386661633030373835363764396535626666
          3461613166663934650a343337666361373465373132363330626464353838326464383830353965
          3834

grafana_user: orinocoz
grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61313131663834666133303631386637343938333262643131373737613963633663633363663733
          6465323337316561636461656232393037313263363262320a336537393562353165316539653065
          64656466323866633232306362636235666630616134653534666137663764336437663531373830
          6638653837336630360a643935323436623465353935613339616435643634396565613632376436
          6239

backup_server_ip: 192.168.42.5
backup_server_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAtnpnME3TsMyvcJyiYawMBod33jkDcFG9Pb1rlxDiXX

backup_user: backup
backup_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33313637383639343138396135376633343337613165336238353135616361316331323761626235
          6661393962636536663939656531613236383232326136660a643830616532386461626261663736
          30663464663433343462366561666239326265346337653837633530346265343133373139333337
          6132316537373933620a386562653434383430386262316361316634636438383736393963346161
          3763

mysql_backup_host: "{{ groups['db_servers'] | reject('eq', mysql_host) | first | default(mysql_host) }}"
github_user_backup: orinocoz
prometheus_server: "{{ groups['prometheus'] | first }}"
loki_server: "{{ groups['loki'] | first }}"

replica_user: replication
replica_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33643338306164333133353964316333343730323064663732613765663832323036346230343235
          3131393963363764646663643664653833303932356663310a653232623034396166656661653037
          37376135663836353261323437626566616339613238353634363337323863626663666336613437
          6532383661343133370a303966623263316631633364313661363463643164386631306630653864
          3135
node_id: "{{ (ansible_port / 100) | int }}"

grafana_port: 3001
agama_port: 8001

agama_container_count: 2
keepalived_vrrp_id: 35
keepalived_auth_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36383237303931643433656530393564643234636364663630626562373433353764343464353962
          3239343337373666646233346161343761616537366462350a666530616436383662346636303033
          33623933636437333462313664653634643338643035393864613934663039336466633866653331
          6435373262666538660a613366326339643133303861643139396265633236656562313165613361
          6463
haproxy_frontend_port: 88
haproxy_stats_port: 9188
keepalived_exporter_version: "1.7.0"

