mysql_host: orinocoz-2 
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31663636633139356436313032666363623437623466306465656337646135653863666563613566
          3438303336306438376332623263366333333265633836390a653333333865323832663134376165
          39393266633739386263333537616534356561376166613234306139656333396632333138343864
          6562333466353332620a323162343161366132326464633031336666653736363238643365373263
          6131

mysql_exporter_user: exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35336233306539396239303132393761363138323139613439373333303165386635363635323362
          3364663435643937303162376364376633353564383864620a336261623164636634343331643537
          35313432346139636262613533626132643033386261626539396139666164336464636438343534
          3634346432353363650a343439316631396530393961353362616362643264396363323661633961
          6537
#mysql_backup_host: "{{ groups['db_servers'] | reject('eq', mysql_host) | first | default(mysql_host) }}"
dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9

dns_allowed_networks:
  - 192.168.42.0/23
  - 127.0.0.0/8

startup_name: acme.ttu

prometheus_exporters:
  mysql:
    port: 9104
  bind:
    port: 9119
  nginx:
   port: 9113
