- name: Update the repository cache and update nginx to latest version
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Install Nginx 1.18.0
  ansible.builtin.apt:
    name: nginx=1.18.0-6ubuntu14.5
    state: present

- name: Nginx configuration
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Restart Nginx if config changed
  ansible.builtin.service:
    name: nginx
    state: restarted
  notify:
    - Restart Nginx

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install from APT prometheus-nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Start Ngnix exporter service
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true

