- name: Update the repository cache and update nginx to latest version
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Install Nginx 
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Nginx configuration
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

      #- name: Flush nginx handlers
      #  ansible.builtin.meta: flush_handlers

- name: Make sure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install from APT prometheus-nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Start Ngnix exporter service
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true

