- name: Update the repository cache and update nginx to latest version
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Install Nginx 1.18.0
  ansible.builtin.apt:
    name: nginx=1.18.0-6ubuntu14.5
    state: present

- name: Copy nginx uWSGI config
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
    owner: root
    mode: '0644'

- name: Restart Nginx if config changed
  ansible.builtin.service:
    name: nginx
    state: restarted
  notify:
    - Restart Nginx

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
