- name: Install Nginx 1.24.0
  ansible.builtin.apt:
    name: nginx=1.24.0-2ubuntu7.5
    state: present
  notify: 
    - Restart Nginx

- name: Copy nginx uWSGI config
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    mode: '0644'

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

