- name: Update the repository cache and update nginx to latest version
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Install Nginx 1.18.0
  ansible.builtin.apt:
    name: nginx=1.18.0-6ubuntu14.5
    state: present
