- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
  notify: Restart HAProxy

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    validate: haproxy -c -f %s
  notify: Restart HAProxy

- name: Ensure HAProxy is started and enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Install prometheus-haproxy-exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter
    state: present
  notify: Restart HAProxy exporter

- name: Configure HAProxy exporter
  ansible.builtin.copy:
    dest: /etc/default/prometheus-haproxy-exporter
    content: |
      ARGS="--haproxy.scrape-uri=http://localhost:{{ haproxy_stats_port }}/haproxy?stats;csv"
    mode: '0644'
  notify: Restart HAProxy exporter

- name: Ensure HAProxy exporter is started and enabled
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true

- name: Add LB CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ dns_nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "lb-{{ idx + 1 }}"
    type: "CNAME"
    value: "{{ item }}.{{ startup_name }}."
  loop: "{{ groups['haproxy'] }}"
  loop_control:
    index_var: idx
  run_once: true
  delegate_to: "{{ groups['dns_primary'][0] }}"
