# InfluxDB configuration
- name: Add InfluxDB GPG key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present
    validate_certs: yes
    keyring: /usr/share/keyrings/influxdata-archive-keyring.gpg

- name: Add InfluxDB APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/influxdata-archive-keyring.gpg] https://repos.influxdata.com/debian stable main"
    state: present
    filename: influxdb.list  # Ensure a unique filename

- name: Install InfluxDB
  ansible.builtin.apt:
    name: influxdb=1.8.10-1
    state: present

- name: Start and enable InfluxDB service
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true

# Telegraf configuration
- name: Install Telegraf repository key
  get_url:
    url: https://repos.influxdata.com/influxdata-archive.key
    dest: /usr/share/keyrings/influxdata-archive-keyring.gpg
    mode: '0644'

- name: Add Telegraf APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/influxdata-archive-keyring.gpg] https://repos.influxdata.com/debian stable main"
    state: present
    filename: telegraf.list  # Ensure a unique filename

- name: Install Telegraf
  ansible.builtin.apt:
    name: telegraf
    state: present

- name: Configure Telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: '0644'
  notify: Restart Telegraf

- name: Start and enable Telegraf service
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true

# Prometheus InfluxDB stats exporter
- name: Install InfluxDB stats exporter
  get_url:
    url:   https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest:  /usr/local/bin/
    mode:  '0500'
    owner: prometheus

- name: Describe the service in '/etc/systemd/system/prometheus-influxdb-stats-exporter.service'
  notify: Restart the system daemon
  template:
    src:  prometheus-influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    mode: '0644'
    
- name: Make sure the InfluxDB stat exporter is started
  service:
    name:    prometheus-influxdb-stats-exporter
    state:   started
    enabled: true

- name: Create the InfluxDB backup directory
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: '0755'

- name: Add cron tab
  ansible.builtin.template:
    src: templates/influxdb-backup.j2
    dest: /etc/cron.d/influx-backup
  notify: Restart cron
