# InfluxDB configuration
- name: Add InfluxDB GPG key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present
    validate_certs: yes
    keyring: /usr/share/keyrings/influxdata-archive-keyring.gpg

- name: Add InfluxDB APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/influxdata-archive-keyring.gpg] https://repos.influxdata.com/debian stable main"
    state: present
    filename: influxdb.list  # Ensure a unique filename

- name: Install InfluxDB
  ansible.builtin.apt:
    name: influxdb=1.8.10-1
    state: present

- name: Start and enable InfluxDB service
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true

# Telegraf configuration
- name: Install Telegraf repository key
  get_url:
    url: https://repos.influxdata.com/influxdata-archive.key
    dest: /usr/share/keyrings/influxdata-archive-keyring.gpg
    mode: '0644'

- name: Add Telegraf APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/influxdata-archive-keyring.gpg] https://repos.influxdata.com/debian stable main"
    state: present
    filename: telegraf.list  # Ensure a unique filename

- name: Install Telegraf
  ansible.builtin.apt:
    name: telegraf
    state: present

- name: Configure Telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: '0644'
  notify: Restart Telegraf

- name: Start and enable Telegraf service
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true
