- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present

- name: Install APT grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Service Grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true

- name: File grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: "0700"
  no_log: true
  notify:
    - Restart Grafana
- name: File datasource.yaml
  ansible.builtin.template:
    src: datasource.yaml.j2
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
  notify:
     - Restart Grafana

- name: File dashboards.yaml
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
  notify:
    - Restart Grafana

- name: Ensure dashboards directory exists
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana

- name: Deploy agama dashboard
  ansible.builtin.copy:
    src: agama.json
    dest: /var/lib/grafana/dashboards/agama.json
    owner: grafana
    group: grafana
    mode: '0640'
  notify:
    - Restart Grafana

- name: Deploy backup dashboard
  ansible.builtin.copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/main.json
  notify:
   - Restart Grafana

- name: File main.json
  ansible.builtin.copy:
    src: backups.json
    dest: /var/lib/grafana/dashboards/backups.json
  notify:
   - Restart Grafana

- name: File mysql.json
  ansible.builtin.copy:
    src: mysql.json
    dest: /var/lib/grafana/dashboards/mysql.json
  notify:
   - Restart Grafana

