- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install APT grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Service Grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true

- name: File grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: "0700"
  no_log: true
  notify:
    - Restart Grafana

