- name: Create Grafana config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/grafana
    - /opt/grafana/provisioning
    - /opt/grafana/provisioning/dashboards
    - /opt/grafana/provisioning/datasources

- name: Deploy grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    owner: "472"
    mode: '0400'
  notify: Restart Grafana container

- name: Deploy datasource configuration
  ansible.builtin.template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasource.yaml
  notify: Restart Grafana container

- name: Deploy dashboard provisioning config
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/dashboards.yaml
  notify: Restart Grafana container

- name: Deploy dashboard JSON files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/grafana/provisioning/dashboards/{{ item }}
  loop:
    - agama.json
    - main.json
    - backups.json
    - mysql.json
    - haproxy.json
  notify: Restart Grafana container

- name: Run Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: always
    ports:
      - "{{ grafana_port }}:3000"
    volumes:
      - /opt/grafana:/etc/grafana
    dns_servers:
      - "{{ hostvars[groups['dns_servers'][0]]['ansible_default_ipv4']['address'] }}"
    dns_search_domains:
      - "{{ startup_name }}"
    log_driver: grafana/loki-docker-driver
    log_options:
      loki-url: "http://{{ loki_server }}:3100/loki/api/v1/push"
