- name: Create directories for Grafana
  file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
  loop:
    - dashboards
    - datasources

- name: Create grafana template file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    mode: '0644'
  notify: Restart grafana-docker
  no_log: true

- name: Create Grafana dashboard template
  ansible.builtin.template:
    src: dashboards.yaml
    dest: /opt/grafana/provisioning/dashboards/dashboards.yaml
    mode: '0644'
  notify: Restart grafana-docker

- name: Run grafana datasource template
  ansible.builtin.template:
    src: datasources.yaml
    dest: /opt/grafana/provisioning/datasources/datasources.yaml
    mode: '0644'
  notify: Restart grafana-docker

- name: Add all dashboard json files
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
  loop:
      - backups.json
      - main.json
      - mysql.json
      - syslog.json
  notify: Restart grafana-docker

- name: Run Grafana in docker
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: always
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"

