- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
      - python3-pymysql
    update_cache: yes
  notify:
    - Restart uWSGI

- name: Copy uWSGI configuration
  ansible.builtin.template:
    src: templates/agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0600'
  no_log: true

- name: Ensure uWSGI service is started and enabled
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true

- name: Ensure that uWsgi log file exists and allow adm group to read it
  ansible.builtin.file:
    path: /var/log/uwsgi/app/agama.log
    state: touch
    access_time: preserve
    modification_time: preserve
    owner: agama  
    group: adm
    mode: '0640'
