- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
      - python3-pymysql
    update_cache: yes

- name: Copy uWSGI configuration
  ansible.builtin.template:
    src: templates/agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0600'
      #no_log: true

- name: Restart uWSGI service if config changed
  ansible.builtin.service:
    name: uwsgi
    state: restarted
  notify:
    - Restart uWSGI

- name: Make sure uWSGI service is started and enabled
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
