- name: Stop daemon systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Change DNS configuration file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
