---
- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Reload rndc
  shell: rndc reload

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart exporter service
  ansible.builtin.service:
    name: bind_exporter
    state: restarted
