- name: Create agama user
  ansible.builtin.user:
    name: agama
    state: present

- name: Create /opt/agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    group: agama

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - python3
      - python3-venv
      - sqlite3
      - python3-flask
      - python3-flask-sqlalchemy
    update_cache: true
    state: present

- name: Download AGAMA application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/main/agama.py
    dest: /opt/agama/agama.py
    owner: agama
    group: agama
    mode: '0755'
