- name: Create Agama build directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    mode: '0755'

- name: Download Agama application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/main/agama.py
    dest: /opt/agama/agama.py
    mode: '0644'
  register: agama_app

- name: Download Agama Dockerfile
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/main/Dockerfile
    dest: /opt/agama/Dockerfile
    mode: '0644'
  register: agama_dockerfile

- name: Build Agama Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      network: host
    state: present
    force_source: "{{ agama_app.changed or agama_dockerfile.changed }}"

- name: Run Agama containers
  community.docker.docker_container:
    name: "agama-{{ item }}"
    image: agama
    state: started
    restart_policy: always
    ports:
      - "{{ agama_port + item }}:8000"
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@db-1.{{  startup_name }}/{{ mysql_database }}"
    dns_servers: "{{ groups['dns_secondary'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
    dns_search_domains:
      - "{{ startup_name }}"
    log_driver: grafana/loki-docker-driver
    log_options:
      loki-url: "http://{{ loki_server }}:3100/loki/api/v1/push"
  loop: "{{ range(agama_container_count) | list }}"
  no_log: true
  tags:
    - agama
    - mysql_switchover

- name: Add web CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ dns_nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "www-{{ idx + 1 }}"
    type: "CNAME"
    value: "{{ item }}.{{ startup_name }}."
  loop: "{{ groups['web_servers'] }}"
  loop_control:
    index_var: idx
  run_once: true
  delegate_to: "{{ groups['dns_primary'][0] }}"
  no_log: true
