- name: Create Agama build directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    mode: '0755'

- name: Download Agama application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/main/agama.py
    dest: /opt/agama/agama.py
    mode: '0644'
  register: agama_app

- name: Download Agama Dockerfile
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/main/Dockerfile
    dest: /opt/agama/Dockerfile
    mode: '0644'
  register: agama_dockerfile

- name: Build Agama Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      network: host
    state: present
    force_source: "{{ agama_app.changed or agama_dockerfile.changed }}"

- name: Run Agama container
  community.docker.docker_container:
    name: agama
    image: agama
    state: started
    restart_policy: always
    ports:
      - "{{ agama_port }}:8000"
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    dns_servers:
      - "{{ hostvars[groups['dns_servers'][0]]['ansible_default_ipv4']['address'] }}"
    dns_search_domains:
      - "{{ startup_name }}"
    log_driver: grafana/loki-docker-driver
    log_options:
      loki-url: "http://{{ loki_server }}:3100/loki/api/v1/push"
  no_log: true
  tags:
    - agama
    - mysql_switchover
