- name: Install mysql
  ansible.builtin.apt:
    name: 
      - mysql-server
      - python3-pymysql
    state: present

- name: Ensure MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: true

- name: Make sure mysql is running
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Override mysql bind address
  ansible.builtin.template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: 
    - Restart Mysql

- name: MySQL Exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter

- name: MySQL Exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'

- name: MySQL Exporter user conf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '0600'
  no_log: true
  notify:
    - Restart MySQL Exporter

- name: Force mysql exporter restart
  ansible.builtin.meta: flush_handlers

- name: MySQL Exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true

- name: Create the mysql backup directory
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
    mode: '0755'

- name: Create MySQL backup user
  community.mysql.mysql_user:
    name: "{{ backup_host }}"
    password: "{{ mysql_backup_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv:
      "{{ mysql_database }}.*:LOCK TABLES,SELECT"
    state: present
  no_log: true

- name: Add MySQL backup user conf
  ansible.builtin.template:
    src: templates/mysql_backup.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: '0600'
  no_log: true

- name: Add cron tab
  ansible.builtin.template:
    src: templates/mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
  notify: Restart cron


