- name: Install mysql
  ansible.builtin.apt:
    name: 
      - mysql-server
      - python3-pymysql
    state: present

- name: Make sure mysql is started and enabled
  service:
    name: mysql
    state: started
    enabled: true

- name: Create mysql database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: Create mysql user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    column_case_sensitive: false
  no_log: true

- name: Ensure MySQL service is started and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Override mysql bind address
  ansible.builtin.template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  no_log: true
  notify: 
    - Restart mysql

- name: Mysql exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter

- name: Mysql exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    column_case_sensitive: false
    host: "%"
  no_log: true
  notify:
    - Restart mysql exporter

- name: Mysql exporter user conf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '0600'
  no_log: true
  notify:
    - Restart mysql exporter

- name: Force mysql exporter restart
  ansible.builtin.meta: flush_handlers

- name: Mysql exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true

- name: Create the mysql backup directory
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
    mode: '0755'

- name: Create mysql backup user
  community.mysql.mysql_user:
    name: "{{ backup_host }}"
    password: "{{ mysql_backup_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv:
      "{{ mysql_database }}.*:LOCK TABLES,SELECT"
    state: present
  no_log: true

- name: Add mysql backup user conf
  ansible.builtin.template:
    src: templates/mysql_backup.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: '0600'
  no_log: true

- name: Add cron tab
  ansible.builtin.template:
    src: templates/mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
  notify: Restart cron

- name: Put replication MySQL server into read_only mode
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname in groups['db_primary'] else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica


- name: Assign CNAME
  include_role:
    name: "dns_record"
  vars:
    service: "{{ inventory_hostname | replace('orinocoz','db') }}"

