- name: Install MySQL
  apt:
    name: 
      - mysql-server
      - python3-pymysql
    state: present

- name: Override MySQL bind address
  ansible.builtin.template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: 
    - Restart MySQL

- name: Ensure MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: true

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  community.mysql.mysql_user:
    column_case_sensitive: true
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Install MySQL Exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: present
#  vars:
    policy_rc_d: 101
# service stopped for this start, automatically starts next boot

- name: MySQL Exporter user
  community.mysql.mysql_user:
    column_case_sensitive: true
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'

- name: Enable mysqld_exporter config path
#  ansible.builtin.lineinfile:
#    path: /etc/default/prometheus-mysqld-exporter
#    regexp: '^ARGS='
#    line: 'ARGS="--config.my-cnf /var/lib/prometheus/.my.cnf"'
#  notify:
#    - Restart MySQL Exporter
  ansible.builtin.template:
    src: mysqld_exporter_path.j2
    dest: /etc/default/prometheus-mysqld-exporter
    owner: prometheus
    group: prometheus
    mode: '0640'
#  notify:
#    - Restart MySQL Exporter
  no_log: true


- name: MySQL Exporter user conf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '0600'
  no_log: true
  notify:
    - Restart MySQL Exporter

- name: Force mysql exporter restart
  ansible.builtin.meta: flush_handlers

- name: MySQL Exporter service
  ansible.builtin.systemd:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true
