- name: Install Loki
  ansible.builtin.apt:
    name: loki
    state: present

- name: Loki service start
  service:
    name: loki
    state: started
    enabled: true

- name: Copy Loki configuration
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/loki/config.yml
  notify: Restart Loki

- name: Create /home/backup/loki directory
  ansible.builtin.file:
    path: /home/backup/loki
    state: directory
    owner: backup
    group: backup
    mode: '0700'

- name: Create Loki backup cron service
  ansible.builtin.template:
    src: backup-cron.j2
    dest: /etc/cron.d/loki-backup
  notify: Restart Loki cron
  no_log: true

- name: Add Loki CNAME record
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ dns_nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "loki"
    type: "CNAME"
    value: "{{ inventory_hostname }}.{{ startup_name }}."
  run_once: true
  delegate_to: "{{ groups['dns_primary'][0] }}"
  no_log: true
