# Influxdb
- name: Restart InfluxDB
  ansible.builtin.service:
    name: influxdb
    state: restarted

# Telegraf
- name: Restart Telegraf
  service:
    name:  telegraf
    state: restarted

# Influx stat exporter
- name: Restart the influxDB stat exporter
  service:
    name: prometheus-influxdb-stats-exporter
    state: restarted

- name: Restart the system daemon
  systemd:
    daemon_reload: true

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
