- name: Create keepalived_script user
  ansible.builtin.user:
    name: keepalived_script
    system: true
    shell: /usr/sbin/nologin
    create_home: true
    home: /home/keepalived_script

- name: Deploy Keepalived check script
  ansible.builtin.template:
    src: check_haproxy.sh.j2
    dest: /home/keepalived_script/check_haproxy.sh
    owner: keepalived_script
    mode: '0755'
  notify: Restart Keepalived

- name: Install Keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Deploy Keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart Keepalived
  no_log: true

- name: Ensure Keepalived is started and enabled
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true

- name: Download keepalived-exporter
  ansible.builtin.get_url:
    url: "https://github.com/mehdy/keepalived-exporter/releases/download/v{{ keepalived_exporter_version }}/keepalived-exporter_{{ keepalived_exporter_version }}_linux_amd64.tar.gz"
    dest: "/opt/keepalived-exporter-{{ keepalived_exporter_version }}.tar.gz"
    mode: '0644'

- name: Extract keepalived-exporter
  ansible.builtin.unarchive:
    src: "/opt/keepalived-exporter-{{ keepalived_exporter_version }}.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/keepalived-exporter
  notify: Restart keepalived-exporter

- name: Deploy keepalived-exporter systemd service
  ansible.builtin.template:
    src: keepalived-exporter.service.j2
    dest: /etc/systemd/system/keepalived-exporter.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart keepalived-exporter

- name: Ensure keepalived-exporter is started and enabled
  ansible.builtin.service:
    name: keepalived-exporter
    state: started
    enabled: true
