- name: Create keepalived_script user
  ansible.builtin.user:
    name: keepalived_script
    system: true
    shell: /usr/sbin/nologin
    create_home: true
    home: /home/keepalived_script

- name: Deploy Keepalived check script
  ansible.builtin.template:
    src: check_haproxy.sh.j2
    dest: /home/keepalived_script/check_haproxy.sh
    owner: keepalived_script
    mode: '0755'
  notify: Restart Keepalived

- name: Install Keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Deploy Keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart Keepalived

- name: Ensure Keepalived is started and enabled
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
