- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Create keepalived_script user
  ansible.builtin.user:
    name: keepalived_script
    state: present

- name: Make sure keepalive is running
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true

- name: Create keepalived home dir
  ansible.builtin.file:
    path: /home/keepalived_script/
    state: directory

- name: Create keepalived config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    no_log: true
  notify: Restart keepalived

- name: Check keepalived script and restart
  ansible.builtin.template:
    src: keepalived_script.sh.j2
    dest: /home/keepalived_script/keepalived_script.sh
    mode: '0744'
    owner: keepalived_script
  notify: Restart keepalived

- name: Download Keepalive exporter
  ansible.builtin.get_url:
    url: https://github.com/mehdy/keepalived-exporter/releases/download/v1.3.2/keepalived-exporter-1.3.2.linux-amd64.tar.gz
    dest: /opt/keepalived-exporter-1.3.2.linux-amd64.tar.gz

- name: Install Keepalived exporter
  ansible.builtin.unarchive:
    src: /opt/keepalived-exporter-1.3.2.linux-amd64.tar.gz
    dest: /usr/local/bin/
    mode: 0755
    remote_src: true

- name: Create keepalive service
  ansible.builtin.template:
    src: keepalived-exporter.service
    dest: /etc/systemd/system/
    mode: '0644'

- name: Make sure keepalive exporter is started
  ansible.builtin.service:
    name: keepalived-exporter
    state: started
    enabled: true

