- name: Reload systemd manager configuration
  ansible.builtin.service:
    name: agama_client
    state: restarted

- name: Restart agama_client service
  ansible.builtin.service:
    name: agama_client
    state: restarted
