- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Make sure Prometheus is enabled and running
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Run Prometheus config template
  ansible.builtin.template:
    src: config.yaml.j2 
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
  notify: Restart Prometheus

- name: Run Prometheus Web External Template
  ansible.builtin.template:
    src: metric.yaml.j2
    dest: /etc/default/prometheus
    mode: '0755'
  notify: Restart Prometheus

- name: Create Prometheus backup cron service
  ansible.builtin.template:
    src: backup-cron.j2
    dest: /etc/cron.d/prometheus-backup
  notify: Restart Prometheus cron
  no_log: true

- name: Add Prometheus CNAME record
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ dns_nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "prometheus"
    type: "CNAME"
    value: "{{ inventory_hostname }}.{{ startup_name }}."
  run_once: true
  delegate_to: "{{ groups['dns_primary'][0] }}"
  no_log: true
