- name: Install APT prometheus
  ansible.builtin.apt:
    name:
      - prometheus

- name: Prometheus yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart Prometheus

- name: Add external URL argument to Prometheus
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify:
    - Restart Prometheus

- name: Prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

