- name: Install Bind
  ansible.builtin.apt:
    name: bind9
    state: present
    update_cache: yes
  become: yes

- name: Ensure Bind is running and enabled
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes
  become: yes

- name: Configure DNS forwarders
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
  become: yes
  notify: Restart bind

- name: Configure master zone
  ansible.builtin.template:
    src: db.master.j2
    dest: /var/cache/bind/db.{{ startup_name }}
    force: no
  become: yes
  when: inventory_hostname in groups['dns_primary']
  notify: Reload rndc

- name: Install Bind exporter
  ansible.builtin.apt:
    name: prometheus-bind-exporter
    state: present
    update_cache: yes
  become: yes

- name: Create systemd service file for prometheus-bind-exporter
  ansible.builtin.template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
  notify:
    - Reload systemd

- name: Ensure Bind exporter is running and enabled
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes
  become: yes

- name: Flush handlers to ensure BIND has latest config
  ansible.builtin.meta: flush_handlers

- name: Add A records for all hosts
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ dns_nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "{{ item }}"
    type: "A"
    value: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  loop: "{{ groups['all'] }}"
  run_once: true
  when: inventory_hostname in groups['dns_primary']

- name: Add backup server A record
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ dns_nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "backup"
    type: "A"
    value: "{{ backup_server_ip }}"
  run_once: true
  when: inventory_hostname in groups['dns_primary']

  - name: Add NS CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ dns_nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "ns-{{ idx + 1 }}"
    type: "CNAME"
    value: "{{ item }}.{{ startup_name }}."
  loop: "{{ groups['dns_servers'] }}"
  loop_control:
    index_var: idx
  run_once: true
  when: inventory_hostname in groups['dns_primary']

