- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present
    update_cache: yes
  become: yes

- name: Make sure bind9 is running and enabled
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes
  become: yes

- name: Configure DNS forwarders
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
  become: yes

- name: Configure master zone
  ansible.builtin.template:
    src: db.master.j2
    dest: /var/cache/bind/db.{{ startup_name }}
  become: yes
  notify: Reload rndc

- name: Download and extract bind9 exporter to /opt
  ansible.builtin.unarchive:
    src: https://github.com/prometheus-community/bind_exporter/releases/download/v0.6.1/bind_exporter-0.6.1.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Create symlink to /usr/local/bin/bind_exporter
  ansible.builtin.file:
    src: /opt/bind_exporter-0.6.1.linux-amd64/bind_exporter
    dest: /usr/local/bin/bind_exporter
    state: link

- name: Create systemd service file for prometheus-bind-exporter
  ansible.builtin.template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
  notify:
    - Reload systemd

- name: Bind exporter service
  ansible.builtin.systemd:
    name: bind_exporter
    state: started
    enabled: true

- name: Configure rev
  ansible.builtin.template:
    src: db.rev.j2
    dest: /var/cache/bind/db.rev
    force: yes
  notify: Restart bind9
  when: inventory_hostname in groups['dns_primary']

- name: Install nsupdate dependency
  ansible.builtin.apt:
    name: python3-dnspython
    state: present

- name: Flush bind handlers
  ansible.builtin.meta: flush_handlers

- name: Add backup record
  community.general.nsupdate:
    key_algorithm: hmac-sha256
    key_name: nsupdate.key
    key_secret: "{{ nsupdate_key }}"
    record: backup
    server: "{{hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address']}}"
    state: present
    type: A
    zone: "{{ startup_name }}"
    value: "{{ backup_host_ip }}"
  register: nsupdate_result
  when: inventory_hostname in groups['dns_primary']

- name: Assign CNAME
  include_role:
    name: "dns_record"
  vars:
    service: "{{ inventory_hostname | replace('orinocoz','ns') }}"

