- name: Install Bind
  ansible.builtin.apt:
    name: bind9
    state: present
    update_cache: yes
  become: yes

- name: Ensure Bind is running and enabled
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes
  become: yes

- name: Configure DNS forwarders
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
  become: yes
  notify: Restart bind

- name: Configure master zone
  ansible.builtin.template:
    src: db.master.j2
    dest: /var/cache/bind/db.{{ startup_name }}
  become: yes
  when: inventory_hostname in groups['dns_primary']
  notify: Reload rndc

- name: Install Bind exporter
  ansible.builtin.apt:
    name: prometheus-bind-exporter
    state: present
    update_cache: yes
  become: yes

- name: Create systemd service file for prometheus-bind-exporter
  ansible.builtin.template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
  notify:
    - Reload systemd

- name: Ensure Bind exporter is running and enabled
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes
  become: yes


