# Update APT cache (once every 24h)
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

# Proemetheus node exporter
- name: Install APT prometheus-node-exporter
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter

- name: Prometheus node exporter service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

# Rsyslog to Telegraf      
- name:   Configure rsyslog to send logs to Telegraf
  notify: Restart rsyslog
  template:
    src:  rsyslog.conf.j2
    dest: /etc/rsyslog.d/rsyslog.conf
    mode: '0644'
    
- name: Make sure ryslog is started
  service:
    name:    rsyslog
    state:   started
    enabled: true

- name: Create backup user with SSH
  ansible.builtin.user:
    name: backup
    state: present
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: true

- name: Create backup restore directory 
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    mode: '0755'
    owner: backup
    group: backup

- name: Create known_hosts for backup user
  ansible.builtin.template:
    src: backup_known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: 0644

- name: Install duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present
