#- name: Ansible ping module
#  ansible.builtin.ping:

# Update APT cache
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

## Create user juri
#- name: Create user juri
#  ansible.builtin.user:
#    name: juri
#    state: present
#   shell: /bin/bash

## Add public key for user juri from github
#- name: Add public key for user juri from github
#  ansible.builtin.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

## Create user roman
#- name: Create user roman
#  ansible.builtin.user:
#    name: roman
#    state: present
#    shell: /bin/bash

## Add public key for user roman from github
#- name: Add public key for user roman from github
#  ansible.builtin.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Add Grafana APT GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository (OSS)
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    filename: grafana
    state: present

- name: Install Prometheus node 
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Ensure node_exporter are started and enabled
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Install Promtail
  ansible.builtin.apt:
    name: promtail
    state: present

- name: Add Promtail user to adm group
  ansible.builtin.user:
    name: promtail
    groups: adm
    append: yes

- name: Ensure Promtail state directory exists
  ansible.builtin.file:
    path: /var/lib/promtail
    state: directory
    owner: promtail
    mode: '0755'

- name: Deploy Promtail configuration
  ansible.builtin.template:
    src: promtail.yaml.j2
    dest: /etc/promtail/config.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Promtail

- name: Ensure Promtail service is started and enabled
  ansible.builtin.service:
    name: promtail
    state: started
    enabled: yes

- name: Create a backup user
  ansible.builtin.user:
    name: backup
    shell: /bin/bash
    home: /home/backup
    create_home: yes
    generate_ssh_key: true

- name: Ensure backup user .ssh directory exists
  ansible.builtin.file:
    path: /home/backup/.ssh
    state: directory
    owner: backup
    group: backup
    mode: '0700'

- name: Deploy known_hosts for backup user
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0644'
    force: yes

- name: Create /home/backup/restore directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0700'

- name: Install Duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present

- name: Install dnspython for nsupdate
  ansible.builtin.apt:
    name: python3-dnspython
    state: present
